blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/yourusername/Red-Pixel/discussions
    about: Please ask and answer questions here
  - name: Documentation
    url: https://github.com/yourusername/Red-Pixel/wiki
    about: Check our documentation for common questions
  - name: Theme Showcase
    url: https://github.com/yourusername/Red-Pixel/discussions/categories/show-and-tell
    about: Show off your site built with Red-Pixel